Styling box
nsquared-team/draw-attention pull request #56
Opened 2024-04-05 20:48 UTC by zeinshhadi

Asana Task : https://app.asana.com/0/1202993069895285/1206835804889510/f

Loom video : https://www.loom.com/share/96da9a72380145f3a00148838707666a?sid=25f5edfa-73a0-468b-bd95-a1a99f28762f

Description : Fixed styling of boxes in more info.

2024-04-06 00:43 UTC, NatalieMac requested changes

2024-04-06 00:43 UTC, NatalieMac commented on public/class-drawattention.php
This is the public-facing code for the front end of the website. The admin code is in admin/class-drawattention-admin.php. You'll see the other 'admin_enqueue_scripts' hooks in that file. We would also want to include the plugin slug prepended to the name of the style.

2024-04-06 00:43 UTC, NatalieMac commented on public/assets/css/custom-field-styles.css
Rather than being a standalone CSS file, this should be in admin/assets/css/admin.css with the other CSS that applies to the admin UI. But, as I was the only frontend dev on this plugin for nearly 10 years, I have a weird sass compiler in use that you don't have access to. If you want to add your code to admin/assets/sass/admin.scss, I can compile it before this PR merges in.

2024-04-08 22:15 UTC, zeinshhadi commented on public/assets/css/custom-field-styles.css
@NatalieMac I will add my code to admin/assets/sass/admin.scss.
 Just to make sure, should I remove the add_action hook and the function used to enqueue a stylesheet I added before ?

2024-04-10 20:12 UTC, zeinshhadi commented
@NatalieMac I added the CSS code to admin.css file as you requested instead of having a standalone CSS file.
[Loom Video](https://www.loom.com/share/df8ce968039346b885bc4e449827ade1?sid=cbf29363-364c-4919-a46c-35d7e9a24304)

2024-04-11 00:27 UTC, NatalieMac approved these changes
@zeinshhadi I went ahead and re-compiled the Sass so this is all looking good now.

2024-04-11 15:15 UTC, tylerdigital approved these changes

2024-04-11 15:15 UTC, merged